### ISSUE TITLE
CircleCI Spectron /  Mocha tests failing in 2.0.0.beta1

### ISSUE THREAD

**Issue by monetizedesign** [electron/electron#12471]
* Electron version: 2.0.0.beta1^
* Operating system: Mac / Linux / CircleCi

### Expected behavior

In stable `1.8.4` version the tests run using Spectron in CircleCi. 

### Actual behavior

Tests do not run and give this error.

```
Error: An unknown server-side error occurred while processing the command.
    at execute(<Function>, "require") - api.js:73:26
type:          RuntimeError
seleniumStack: 
  type: UnknownError
  message: An unknown server-side error occurred while processing the command.
  orgStatusMessage: unknown error: The inAppPurchase module can only be used on macOS
Error: The inAppPurchase module can only be used on macOS
    at Object.<anonymous> (/home/circleci/repo/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:4:9)
    at Object.<anonymous> (/home/circleci/repo/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:16:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as inAppPurchase] (/home/circleci/repo/node_modules/electron/dist/resources/electron.asar/browser/api/exports/electron.js:11:16)
  (Session info: content shell=)
  (Driver info: chromedriver=2.29 (8e8216e581c512667203931f81c1a1ead47222e5),platform=Linux 4.4.0-116-generic x86_64)
```

### How to reproduce

Run Spectron + Mocha with CircleCI using this config.yml

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install --save-dev electron-chromedriver
      - run: npm test
```
