### ISSUE TITLE
[Bug] 3.0.0-beta1 CSS3 `-webkit-app-region: drag` not working

### ISSUE THREAD

**Issue by JieJiSS** [electron/electron#13358]
* Electron Version: 3.0.0-beta1
* Operating System (Platform and Version): macOS
* Last known working Electron version: 2.0.2

**Expected Behavior**
```css
html, body, * {
    -webkit-app-region: drag;
    -webkit-user-select: none;
    cursor: default;
}
```
should allow users to move the position of the window by dragging it directly.

**Actual behavior**
The window is not draggable.
The `cursor` and `-webkit-user-select` properties work well.

**To Reproduce**
copy the CSS above, paste it into a frameless app's `<style>` tag, and run the app.

**Screenshots**

**Additional Information**
