### ISSUE TITLE
White border lines appear in transparent windows

### ISSUE THREAD

**Issue by hoythan** [electron/electron#15641]
v4.0.0-nightly.20181010
MacOS 10.14.1 (18B75)  **Dark Mode**

In the new version, the transparent window will display a white border line at the top.

![](https://ws2.sinaimg.cn/large/006tNbRwly1fx102oj1a8j30eo066dg2.jpg)

### window option:
```javascript
{			
    width: 400,
    height: 600,
    resizable: false,
    frame: false,
    transparent: true,
    skipTaskbar: false,
    movable: true,
    maximizable: false,
    alwaysOnTop: true,
    fullscreenable: false,
    acceptFirstMouse: true,
    autoHideMenuBar: true,
    hasShadow: false,
    show: true
}
```

### css styles
```css
html body #app {
    height: 100%;
    padding-top: 13px;
    background-color: transparent;
}
```
