### ISSUE TITLE
Issues with rounded corners

### ISSUE THREAD

**Issue by ThatTonybo** [electron/electron#18203]
* **Electron Version:**
  * v3.0.10
* **Operating System:**
  * Windows 10 Pro (1809)
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
I applied `border-radius` to the body and my internal container element to get rounded corners on the window.

### Actual Behavior
They stayed very square, with no effect when using `transparent: true` in the create window, or any other fixes I've found.

### To Reproduce
- Create an electron app
- Add `border-radius` to the body
- No result

### Screenshots
![image](https://user-images.githubusercontent.com/28176227/57341986-df246380-717f-11e9-9e2d-af979dcdfee1.png)

### Additional Information
Here's my CSS and HTML layout:
```css
body {
    background: transparent;
    margin: 0 0;
    height: 100%;
    border-radius: 12px !important;
}

.container {
    background: #0E0E0F;
    border-radius: 12px !important;
}

.titlebar {
    background: #0E0E0F;
    border-top-left-radius: 12px;
    border-top-right-radius: 12px;
}
```
```html
<body>
    <div class="container">
        <div class="titlebar" style="float: left;">
            <a onclick="bclose()" class="b close">&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a onclick="bminimize()" class="b minimize">&nbsp;&nbsp;&nbsp;&nbsp;</a>
        </div>
    </div>
</body>
```
