### ISSUE TITLE
Javascript returns incorrect computed css sizes, differs from DevTools, on Windows

### ISSUE THREAD

**Issue by usimarit** [electron/electron#19720]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.9 and latest
* **Operating System:**
  *  Windows 10 (1903)
  * ~~Ubuntu~~: Works perfectly
* **Last Known Working Electron version:**
  * None

### Expected Behavior <a name="1"></a>

_offset(height/width)_, _scroll(height/width)_, _client(height/width)_ and _window.getComputedStyle(element).(height/width)_ return **correct values** like in DevTools when using ```height: fit-content``` and ```width: fit-content```

### Actual Behavior

**Incorrect values**

### To Reproduce

My css:
```css
html {
  display: block;
  overflow: hidden;
  height: fit-content;
  width: fit-content;
}

body {
  font-family: "Roboto";
  background-color: whitesmoke;
  padding: 0;
  margin: 0;
  transition: 100ms all ease-in-out;
  border: 1px solid #375e97;
  display: flex;
  flex-direction: column;
  justify-content: stretch;
  align-items: stretch;
  overflow: auto;
  box-sizing: border-box;
  height: fit-content;
  width: fit-content;
  max-height: 720px;
}

body .popup_detail p {
  display: block;
  margin: 0;
  padding: 0;
  font-size: 14pt;
  color: black;
  max-width: 450px;
  word-wrap: break-word;
}

body .popup_detail h5 {
  display: block;
  margin: 0;
  padding: 0;
  color: grey;
  word-wrap: none;
}

body .popup_detail {
  margin: 0;
  padding: 10px;
  display: flex;
  flex-direction: column;
  justify-content: stretch;
  align-items: stretch;
  height: min-content;
  width: max-content;
  box-sizing: border-box;
}
```
My html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="../stylesheets/style.css" />
    <title>Title</title>
  </head>
  <body>
    <script type="text/javascript">
      require("../../components/popup.js");
    </script>
  </body>
</html>
```
My javascript
```javascript
const ipcRenderer = require("electron").ipcRenderer;
var body = document.body;
function changeElement(arg) {
  // Display the content
  body.innerHTML = `<div class="popup_detail"><h5 id="source_lang">${
    arg.source_lang
  }</h5><p id="text">${
    arg.text
  }</p></div><div class="popup_detail"><h5 id="target_lang">${
    arg.target_lang
  }</h5><p id="translated_text">${arg.translated_text}</p></div>`;
}
function sendSize(sender) {
  let ele = document.documentElement;
  sender.send(
    "async-show-trans-reply",
    JSON.stringify({
      height: ele.offsetHeight,
      width: ele.offsetWidth
    })
  );
}
ipcRenderer.on("async-show-trans", (event, arg) => {
  // Send back the whole document height
  changeElement(arg);
  // for ipcMain to resize the pop up "framelessWin"
  sendSize(event.sender);
});
```
My ipcMain
![Annotation 2019-08-12 215756](https://user-images.githubusercontent.com/28498441/62876513-4b020380-bd4f-11e9-8142-8f55f9ab5c9f.png)

### Screenshots

In DevTools:
![Annotation 2019-08-12 215622](https://user-images.githubusercontent.com/28498441/62876616-8a305480-bd4f-11e9-96fd-c6f85729cefd.png)

Output values from javascript (the ```data``` in ipcMain):
![Annotation 2019-08-12 215700](https://user-images.githubusercontent.com/28498441/62876633-99af9d80-bd4f-11e9-97d0-e7d6011335a8.png)

### Additional Information

I've tried all kind of sizes [above](#1) but they still give wrong values (both height and width). I tried setting html ```height: 100px``` and ```width: 100px``` and it gave correct values, but not with the dynamic size.

I'll be glad if you guys can help, thanks.
