### ISSUE TITLE
Bring in own user agent styles

### ISSUE THREAD

**Issue by NetOpWibby** [electron/electron#22055]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I would like to provide my own user agent stylesheet to Electron.

### Proposed Solution
Allow the capability to provide own user agent stylesheet to Electron.

### Alternatives Considered
Recompile Chromium/Electron...

**Comment by devingfx** [comment]
I would love to have
 ```CSS
html, body {
	width: 100%;
	height: 100%;
	margin: 0;
}
* { box-sizing: border-box }
```
by  default ...
