### ISSUE TITLE
iframe inside a webview doesn't maximize on requestFullScreen

### ISSUE THREAD

**Issue by rzhao271** [electron/electron#27719]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.21, though as far back as 5.0.13
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
1. Put an iframe inside of a webview
2. Call requestFullScreen on the inner iframe
3. Expect the iframe to expand and take up the entire window

### Actual Behavior
For step 3, neither the iframe nor the webview expand fully. Only the window itself becomes full-screen.

### To Reproduce
Check the "iframe inside webview" case of this minimal repro:
[fiddle.zip](https://github.com/electron/electron/files/5968821/fiddle.zip)

### Screenshots
On an earlier version of the fiddle attached above:

![electron-iframe-webview](https://user-images.githubusercontent.com/7199958/107708227-0030b700-6c78-11eb-9c2b-cddd1d0a3cee.gif)

**Comment by miniak** [comment]
Similar issue can be reproduces with the YouTube player
[youtube.zip](https://github.com/electron/electron/files/6712165/youtube.zip)

**Comment by miniak** [comment]
iframe fullscreen
![Screen Shot 2021-06-24 at 11 14 31 PM](https://user-images.githubusercontent.com/1281234/123333502-1f9ef100-d542-11eb-9a72-be4826b27a3c.png)

webview fullscreen
![Screen Shot 2021-06-24 at 11 15 30 PM](https://user-images.githubusercontent.com/1281234/123333537-2b8ab300-d542-11eb-9aff-6eb9fca66de6.png)

**Comment by miniak** [comment]
another repro
[fullscreen.zip](https://github.com/electron/electron/files/6712195/fullscreen.zip)

**Comment by miniak** [comment]
normal size
<img width="912" alt="Screen Shot 2021-06-24 at 11 18 01 PM" src="https://user-images.githubusercontent.com/1281234/123333878-976d1b80-d542-11eb-9cab-7e39b38a2605.png">

iframe fullscreen
![Screen Shot 2021-06-24 at 11 18 11 PM](https://user-images.githubusercontent.com/1281234/123333915-a3f17400-d542-11eb-980d-31ffc7a6ddee.png)

webview fullscreen
![Screen Shot 2021-06-24 at 11 18 05 PM](https://user-images.githubusercontent.com/1281234/123333959-b10e6300-d542-11eb-806d-658662bd00c6.png)

**Comment by miniak** [comment]
Exiting using the ESC key is also broken with the webview, but not with iframe

**Comment by miniak** [comment]
@rzhao271 it looks like it affects any element inside of the webview, not just iframe. Check my repros.

**Comment by zcbenz** [comment]
It seems that after HTML5 fullscreen, the iframe will get some CSS applied to it:

```css
:not(:root):fullscreen {
    object-fit: contain;
    position: fixed !important;
    top: 0px !important;
    right: 0px !important;
    bottom: 0px !important;
    left: 0px !important;
    box-sizing: border-box !important;
    min-width: 0px !important;
    max-width: none !important;
    min-height: 0px !important;
    max-height: none !important;
    width: 100% !important;
    height: 100% !important;
    transform: none !important;
    margin: 0px !important;
}

iframe:fullscreen {
    border-width: initial !important;
    border-style: none !important;
    border-color: initial !important;
    border-image: initial !important;
    padding: 0px !important;
}
```

But webview gets no such style.
