### ISSUE TITLE
[Feature Request]: Add scale factor or original bounds in pixels to display object of screen.getAllDisplays() API.

### ISSUE THREAD

**Issue by freddy-daniel** [electron/electron#38950]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current implementation of the screen.getAllDisplays() API in ElectronJS provides bounds in DIP (device-independent pixel) points, but it lacks a scale factor or original bounds in pixels. This limitation makes it difficult to obtain the actual bounds in pixel values.

### Proposed Solution

I kindly request the addition of either a scale factor or the original bounds in pixels to the display object. This enhancement would improve usability by allowing developers to directly access and work with the actual pixel bounds.

### Alternatives Considered

If we have scale factor, we can calculate pixels.

### Additional Information

Having access to the scale factor or original bounds in pixels would be valuable for precise positioning and calculations based on pixel values. It would eliminate the need for developers to perform manual conversions, streamlining their code and improving productivity.

This feature would enable developers to build more accurate and responsive applications that adapt seamlessly to different screen configurations. It aligns with industry standards and best practices for working with display bounds, providing a more intuitive and efficient API for ElectronJS users.

Thank you for considering this feature request. I appreciate your dedication to improving ElectronJS and supporting the developer community.

**Comment by freddy-daniel** [comment]
Currently, display bounds are provided in DIP)format, and the width and height can be derived using the scaleFactor associated with the current display object. However, the issue arises when the bounds are based on the scaleFactor of the primary display, leading to incorrect calculations for secondary displays.

For example, if the primary display's actual resolution is 1920 x 1080 and the scaleFactor is 1.25, the derived resolution becomes 1536 x 864. Now, consider a scenario with an extended secondary display positioned to the right of the primary display. The display bounds of the secondary display might appear as follows:

**Extended Secondary Display object**
```yaml
{
  id: 2,
  label: 'External Display',
  bounds: { x: 1536, y: 0, width: 1024, height: 768 },
  ...
  size: { width: 1024, height: 768 },
  ...
  scaleFactor: 1
}

```

Provided bounds value of x=1536 is actually 1920, but there's no way to get this. It would be better if we include value like boundsScaleFactor, so i can calculate actual bounds in pixels.

**Expected Extended Secondary Display object**
```yaml
{
  id: 2,
  label: 'External Display',
  bounds: { x: 1536, y: 0, width: 1024, height: 768 },
  boundsScaleFactor: 1.25,
  ...
  size: { width: 1024, height: 768 },
  ...
  scaleFactor: 1
}

```
