### ISSUE TITLE
Option to disable overscroll on OS X

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5397]
It doesn't look very good for "native" apps to overscroll when scrolling. Would be nice to have a BrowserWindow option to disable overscroll

![untitled12](https://cloud.githubusercontent.com/assets/170270/15033357/fc36e32e-1293-11e6-8cdc-6c17b0f504dd.gif)

-

* Electron version: 0.37.8
* Operating system: OS X 10.11.4

**Comment by mnquintana** [comment]
You can always add this to your CSS declarations to disable elastic scrolling:

```css
html,
body {
  height: 100%;
  width: 100%;
  overflow: auto;
}
```

Does that about cover what you're looking for?
