### ISSUE TITLE
savePage fails to save images linked in css files

### ISSUE THREAD

**Issue by justinmchase** [electron/electron#5627]
* Electron version: 0.37.8
* Operating system: osx

I'm using the [savePage](http://electron.atom.io/docs/api/web-contents/#webcontentssavepagefullpath-savetype-callback) api (with the `'HTMLComplete'` option).

If my page has an image purely in css then the `savePage` function doesn't actually save that file locally. For example:
```css
div.mainContent {
 background: url(/img/path/to/image.png) 0 0 repeat;
}
```

The file is not saved to disk and it then fails to load due to the relative path.

**Comment by justinmchase** [comment]
It also fails to save fonts locally.
```css
@font-face{
  font-family:'Example';
  src:url(example.eot);
}
```

example.eot is not saved to disk.
