### ISSUE TITLE
webview.preload fails when webSecurity is disabled

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#5719]
* Electron version: 1.2.0
* Operating system: OS X 10.11.5

webview preload attribute seems to be broken in Electron 1.2.0/Chrome 51 (worked with 1.1.3/Chrome 50).

Here is how I used it (successfully) on versions prior to 1.2.0:
`@webview.preload = "file://#{app.getAppPath()}/js/player-preload.js"`

Tried to put it in the HTML webview tag directly as attribute, same thing.

Note: No error in the Console though, it's just that the script is never actually executed.

**Comment by kevinsawicki** [comment]
@romaincointepas can you share the options you are passing to the `BrowserWindow` constructor for the window containing the webview?

**Comment by romaincointepas** [comment]
Sure, here it is:

```
win = new BrowserWindow(
    x: winState.x
    y: winState.y
    width: winState.width
    height: winState.height
    show: false
    backgroundColor: '#101010'
    titleBarStyle: 'hidden'
    webPreferences:
      plugins: true
      allowDisplayingInsecureContent: true
  )
```
