### ISSUE TITLE
<webview> "resizes" when toggle hidden.

### ISSUE THREAD

**Issue by kenan2002** [electron/electron#5934]
* Electron version: 1.2.1
* Operating system: Windows

I did what it said in http://electron.atom.io/docs/api/web-view-tag/#css-styling-notes to hide <webview>, but <webview> "flashes" when swtiched hidden/shown. In other words, it "resizes" when shown.

sample code here:

```css
    .container {
      position: relative;
      width: 800px;
      height: 600px;
    }

    webview {
      display: flex;
    }

    .container webview {
      flex: 0 1;
      width: 0;
      height: 0;
    }

    .container webview.active {
      width: 100%;
      height: 100%;
    }
```

```html
    <button id="tab1" type="button" name="button">Tab 1</button>
    <button id="tab2" type="button" name="button">Tab 2</button>

    <div class="container">
      <webview id="wv1" src="https://github.com/atom/atom" class="active"></webview>
      <webview id="wv2" src="https://github.com/atom/electron"></webview>
    </div>
```

```javascript
      const tab1 = document.getElementById('tab1');
      const tab2 = document.getElementById('tab2');
      const wv1 = document.getElementById('wv1');
      const wv2 = document.getElementById('wv2');

      tab1.onclick = () => {
        wv1.classList.add('active');
        wv2.classList.remove('active');
      };

      tab2.onclick = () => {
        wv1.classList.remove('active');
        wv2.classList.add('active');
      };
```
