### ISSUE TITLE
High DPI support on Linux

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#615]
Chromium already had some basic support for high DPI on Linux, we should enable it in atom-shell.

**Comment by Nek-** [comment]
![capture du 2015-03-12 18 10 52](https://cloud.githubusercontent.com/assets/972456/6623421/32018b0e-c8e3-11e4-93be-03c8d3f4885e.png)
Looks like it doesnt work at all...

**Comment by devTristan** [comment]
Same as above. This fixes it, but I wish it didn't:

```css
body {
  zoom: 2;
}
atom-text-editor {
  zoom: 0.5;
  font-size: 200%;
}
```

**Comment by niedzielski** [comment]
I'm not sure what the recommended configuration is but @devTristan's snippet seems to work well.

**Comment by devTristan** [comment]
Updated to handle overlays properly (jshint etc):

```css
body {
  zoom: 2;
}
atom-text-editor {
  zoom: 0.5;
  font-size: 200%;
}
atom-overlay>* {
  zoom: 2;
}
```
