### ISSUE TITLE
Window title bar is "still there" when frame: false, screws up cursor (macOS)

### ISSUE THREAD

**Issue by kurisubrooks** [electron/electron#6725]
* Electron version: v1.3.2
* Operating system: macOS 10.11 (El Capitan)

For some reason, and I haven't noticed any particular pattern here, changing the cursor on elements will sometimes just not work, at all. I've also seen this bug happen in Discord (uses electron), as well as many of my programs that i've developed. 

Just now I did some googling, and can confirm that this bug does not exist in Chrome itself, but rather seems to be an issue isolated to Electron. 

Just noticed it in a `frame: false` window, but I also observe this when there is no modification to the window itself. 

Please let me know if you need any more information.

**Comment by kurisubrooks** [comment]
Beginning to think this may be similar to #5723.

**Comment by kurisubrooks** [comment]
Here you are: [Sample.zip](https://github.com/electron/electron/files/402180/Archive.zip)

Start it with
```
npm install
npm start
```

**Comment by kurisubrooks** [comment]
Notice that the buttons in the top right, have the cursor correct on the bottom portion only. Once the mouse moves into the upper half, the cursor reverts back to the default cursor. There's nothing in the CSS that enforces this behaviour, and i've confirmed this by checking in both Firefox and Chrome.

**Comment by MarshallOfSound** [comment]
OK so I fixed your CSS so the drag region is actually correct (the button shouldn't be drag region)

```css
.window_frame {
    display: flex;
    justify-content: space-between;

    background: #0778CB;
    color: white;
}

.window_frame .window_title {
  padding: 10px 12px;
  flex: 1;
  -webkit-app-region: drag;
}

.window_frame .window_controls {
  padding: 10px 12px;
}

.window_frame .window_controls span {
    position: relative;
    cursor: pointer;
    top: 2px;
    display: inline-block;
}
```

However the bug is still present (but more obvious what it appears to be).

@zcbenz It looks like the hidden frame border is "still there" just hidden and therefore adjusts the cursor.  Interestingly click events are still fired through it.  This appears to be a macOS specific frameless window bug.
