### ISSUE TITLE
Frameless Electron App not dragging via screen

### ISSUE THREAD

**Issue by salmazov** [electron/electron#8706]
* Electron version:
v.1.4.15
* Operating system:
Windows 10

### Expected behavior
Frameless window with settings:

```js
  win = new BrowserWindow({width: 800,
   height: 600,
   frame: false,
   resizable: false
 })
```

and this CSS:

```css
html, body {
	-webkit-app-region: drag;
    -webkit-user-select: none;
	background-color: #ccc;
}
```

and this HTML:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <link rel="stylesheet" type="text/css" href="app.css">
  </head>
  <body style="-webkit-app-region: drag;">
```

shoud Drag'n'Drop via Screen

### Actual behavior
Electron Application when started don't work as expected. I can't drag it via screen.

### How to reproduce
Copy-paste code from Quick Start Guide from official Electron Doc page.

In Terminal:
npm install -g electron

**Comment by MarshallOfSound** [comment]
Are your Dev tools open?

**Comment by salmazov** [comment]
And yes, and no. No effect.

**Comment by kevinsawicki** [comment]
@salmazov having trouble reproducing this on Windows 10.

Does your page have any content? I had to tweak your example a bit to make the `<body>` the size of the window so it was draggable.

```css
html, body {
	-webkit-app-region: drag;
  -webkit-user-select: none;
	background-color: #ccc;
  height: 100%;
  width: 100%;
  margin: 0;
  padding: 0;
}
```
